export const CUSTOMER_ZONING_ASSISTANT_ROUTE_ID = 'customer-zoning-agent'
export const LEGACY_CUSTOMER_ZONING_ASSISTANT_ROUTE_ID = 'customer-zoning-team'

export const CUSTOMER_ZONING_ASSISTANT_ROUTE_IDS = [
  CUSTOMER_ZONING_ASSISTANT_ROUTE_ID,
  LEGACY_CUSTOMER_ZONING_ASSISTANT_ROUTE_ID,
] as const
